// Substitua o seu array 'mockOrdensDeServico' por este:

export const mockOrdensDeServico = [
  // --- Coluna Pendente (2 itens) ---
  {
    id: '1',
    codigo: "OS-101",
    cliente_id: 1,
    cliente_nome: "Acme Corp", // Campo de JOIN para o card
    colaborador_id: 10,
    motorista_id: null,
    motorista_nome: "Aguardando", // Campo de JOIN para o card
    veiculo_id: null,
    origem_cidade: "São José dos Campos",
    origem_uf: "SP",
    destino_cidade: "Rio de Janeiro",
    destino_uf: "RJ",
    distancia_km: 450,
    valor: 1800.50,
    peso_kg: 1200,
    status: "Pendente",
    data_coleta: null,
    data_entrega_prevista: "2025-11-19T00:00:00", // Data para o card
    data_entrega: null,
    observacoes: "Carga frágil, paletizada. Coletar após as 14h.",
    criado_em: "2025-11-16T08:30:00",
  },
  {
    id: '2',
    codigo: "OS-102",
    cliente_id: 2,
    cliente_nome: "Tech Solutions",
    colaborador_id: 11,
    motorista_id: null,
    motorista_nome: "Aguardando",
    veiculo_id: null,
    origem_cidade: "Jacareí",
    origem_uf: "SP",
    destino_cidade: "Belo Horizonte",
    destino_uf: "MG",
    distancia_km: 580,
    valor: 2200.00,
    peso_kg: 850,
    status: "Pendente",
    data_coleta: null,
    data_entrega_prevista: "2025-11-20T00:00:00", // Data para o card
    data_entrega: null,
    observacoes: "Coletar no galpão 3. Falar com Sr. Jonas.",
    criado_em: "2025-11-16T09:15:00",
  },
  
  // --- Coluna Em Andamento (2 itens) ---
  {
    id: '3',
    codigo: "OS-103",
    cliente_id: 3,
    cliente_nome: "Varejo Total",
    colaborador_id: 10,
    motorista_id: 201,
    motorista_nome: "Carlos Silva",
    veiculo_id: 301,
    origem_cidade: "Taubaté",
    origem_uf: "SP",
    destino_cidade: "Curitiba",
    destino_uf: "PR",
    distancia_km: 670,
    valor: 2500.00,
    peso_kg: 1500,
    status: "Em Andamento",
    data_coleta: "2025-11-15T10:00:00",
    data_entrega_prevista: "2025-11-17T00:00:00", // Data para o card
    data_entrega: null,
    observacoes: "Em trânsito. Motorista ciente do prazo.",
    criado_em: "2025-11-14T14:00:00",
  },
  {
    id: '4',
    codigo: "OS-104",
    cliente_id: 1,
    cliente_nome: "Acme Corp",
    colaborador_id: 11,
    motorista_id: 202,
    motorista_nome: "Ana Pereira",
    veiculo_id: 302,
    origem_cidade: "São Paulo",
    origem_uf: "SP",
    destino_cidade: "Vitória",
    destino_uf: "ES",
    distancia_km: 880,
    valor: 3100.00,
    peso_kg: 900,
    status: "Em Andamento",
    data_coleta: "2025-11-16T10:00:00",
    data_entrega_prevista: "2025-11-18T00:00:00", // Data para o card
    data_entrega: null,
    observacoes: "Cliente solicitou entrega apenas em horário comercial (08h-18h).",
    criado_em: "2025-11-15T11:00:00",
  },

  // --- Coluna Concluído (2 itens) ---
  {
    id: '5',
    codigo: "OS-105",
    cliente_id: 2,
    cliente_nome: "Tech Solutions",
    colaborador_id: 10,
    motorista_id: 201,
    motorista_nome: "Carlos Silva",
    veiculo_id: 301,
    origem_cidade: "Caçapava",
    origem_uf: "SP",
    destino_cidade: "Santos",
    destino_uf: "SP",
    distancia_km: 180,
    valor: 950.00,
    peso_kg: 500,
    status: "Concluído",
    data_coleta: "2025-11-13T09:00:00",
    data_entrega_prevista: "2025-11-14T00:00:00", // Data para o card
    data_entrega: "2025-11-14T16:30:00",
    observacoes: "Entrega finalizada com sucesso. Canhoto assinado por Maria.",
    criado_em: "2025-11-12T10:00:00",
  },
  {
    id: '6',
    codigo: "OS-106",
    cliente_id: 3,
    cliente_nome: "Varejo Total",
    colaborador_id: 11,
    motorista_id: 202,
    motorista_nome: "Ana Pereira",
    veiculo_id: 302,
    origem_cidade: "Aparecida",
    origem_uf: "SP",
    destino_cidade: "Campos do Jordão",
    destino_uf: "SP",
    distancia_km: 80,
    valor: 600.00,
    peso_kg: 300,
    status: "Concluído",
    data_coleta: "2025-11-10T11:00:00",
    data_entrega_prevista: "2025-11-10T00:00:00", // Data para o card
    data_entrega: "2025-11-10T15:00:00",
    observacoes: "Entrega concluída. Cliente satisfeito.",
    criado_em: "2025-11-09T08:00:00",
  }
];